### ISSUE TITLE
To Do List

### ISSUE THREAD

**Issue by EdenReuveni** [galbar07/The-Maze-Of-Waze-Navigation-Game#1]
- [ ] resizeing gui window

- [x] algorithm for collecting fruits

- [ ] result table for wiki (for every stage)

- [x] extra window on compiletion

- [x] time to end of game option

- [x] placeing robost and fruits where mouse clicked (on manual mode)

- [x] making sure a fruit is on an edge

- [x] decrease radius for eating a fruit 

- [x] what if two robots are on the same edge

- [x] class diagram

- [x] tests for robot class, fruit class, algo class

- [x] KML

- [x] placing robots smartly

**Comment by galbar07** [comment]
done
